### ISSUE TITLE
License Violations

### ISSUE THREAD

**Issue by Mar0xy** [164-life/re_lovers#13]
I got directed towards this by someone and found out that a lot of commits/changes from Sharkey were imported without ever giving any attribution which is a direct violation towards the AGPLv3 license which states `License and copyright notice` as a condition which in this area is not provided while using a ton of Sharkey code.

**Comment by 164-life** [comment]
How should the copyright notice be displayed?
It's hard to type a copyright notice in code...
So we are currently using Sharkey code for all code related to the Mastodon API, import functionality.
We would like to strictly adhere to the AGPL v3 rules, so we will do it right.

**Comment by Mar0xy** [comment]
It can be displayed in anyway you like it just has to be shown somewhere.

**Comment by 164-life** [comment]
> It can be displayed in anyway you like it just has to be shown somewhere.
> 
> Be it the README, Code or in Frontend

We have included this information in README.md.
Please check it.

**Comment by 164-life** [comment]
The execution is completed and resolved, and the process is closed.
